;=======================================================
; 此文件用于MsgTool提取时的自定义人名配置
; 格式: [占位符] = 十六进制代码 (经过XOR解密[一般是xorFF]后的、不带0x前缀的十六进制码)
; 在ConfigurationID后填入相关ID可以读取相应的配置
; 8193'  # "％" character used in ver4，早期部分游戏仅可改名，对应shift-jis下的％，目前不清楚GBK会有什么反应;
;========================================================================
; 以下为全局控制命令：
; 配置选项ID填写，不填或填写无效ID，默认为0
ConfigurationID= 0
; 它会交换默认人名与自定义人名的msg内容
AdjustBranchMessages= False
; 若有多个paramsID，在以下定义首个分支的msg将与第几个ID的msg互换
AdjustMsgID= 1
; 展示替换信息，仅在AdjustBranchMessages启用时可被启用
AdjustMsgDetails= True
; 长度检测校验：仅在回注时有效
MsgLengthCheck= True
; 长度修正：按固定的字数进行换行符的重新划分，并生成message_fix.txt，仅在回注时有效
MsgLengthFix= True
; 长度修正的一行最大字符数设置
; Simhei下文本框一行最大显示数为37.5字，BACKLOG为30.5
; Simhei下文本框的最大行数为4行（第4行会遮挡），BACKLOG为4行
; Simhei下一行最大显示数为30，最大行数为3
MsgLengthSet= 29



; 以下为局部配置控制命令

; 目前默认BB社与南瓜社通用
■[0][Default configuration]
; [FirstName]: 自定义名
[FirstName] = F040
; [FirstName]_Len: 自定义名在显示中的预估字符数，用于后续的长度检测与修正，以下类似
[FirstName]_Len = 2
; [Surname]: 自定义姓
[Surname] = F041
[Surname]_Len = 2
; 如果未来发现新的人名控制码，直接在这里添加即可，注意添加对应的显示字符数，否则默认为3字符
; [Nickname] = F042
; [Nickname]_Len = 2
; 回注时是否加密，开启后会对回注文本进行XOR加密
EncryptEnabled= True
; 回注时的加密密钥:EncryptKey仅在EncryptEnabled开启时被采纳，范围由0x00到0xFF，其中0x00为不加密
EncryptKey= FF
; GBK编码校验
GBKCheck= True

■[1][Steam/UTF-8]
[FirstName] = 7B464E7D
[FirstName]_Len = 2
EncryptEnabled= True
EncryptKey= FF
GBKCheck= False
; 以下两项若不填写，则使用在命令行中输入的编码
; 强制覆盖的读取编码
ReadingEncoding= utf-8
; 强制覆盖的写入编码
WritingEncoding= utf-8